### PR TITLE
Add log files, etc. to report.

### PR DESCRIPTION
**Pull request by stuartjamesmcnicholas**
Logs, stdout (and possibly other .txt files) are added to a sub fold of job run details.

Additionally a "Copy to clipboard" button is added which copies contents of all log files to clipboard.

Remake report will activate these features.

### CODE REVIEW

**Comment by stuartjamesmcnicholas** [comment]
I guess the Log files could be top level rather than sub fold of job run? Any thoughts?

**Comment by paulsbond** [comment]
I would have Log files as a sibling to Job run details. However, It would be good to have a fold per file which is unexpanded by default. I like the copy to clipboard idea. I guess it copies all the files to the clipboard, which is why it would be useful to have a Log files parent.

**Comment by MartinMalyMM** [comment]
> I guess the Log files could be top level rather than sub fold of job run? Any thoughts?

We have stdout.txt only in top level I think.

**Comment by stuartjamesmcnicholas** [comment]
> We have stdout.txt only in top level I think.

Nah, there all at same level. But you have to scroll to see others. I think I like Paul's folder per file idea. I will try it.

**Comment by stuartjamesmcnicholas** [comment]
OK, all that done. Now looks like:
Screenshot 2024-12-13 at 17 13 58

**Review by paulsbond — APPROVED** [review]

**Pull request merged**
