### PR TITLE
Fix occupancy refinement group editor.

### PR DESCRIPTION
**Pull request by stuartjamesmcnicholas**

### CODE REVIEW

**Comment by MartinMalyMM** [comment]
When I click on a Group ID value, I can see this in the terminal, is it OK?
Traceback (most recent call last):
  File "/home/martin/ccp4i2-github/qtgui/CCP4ModelWidgets.py", line 1541, in setEditorData
    editor.setText(value)
TypeError: 'PySide2.QtWidgets.QLineEdit.setText' called with wrong argument types:
  PySide2.QtWidgets.QLineEdit.setText(int)
Supported signatures:
  PySide2.QtWidgets.QLineEdit.setText(str)

I added a check whether the Group IDs are unique in prosmart_refmac_gui.py

**Comment by stuartjamesmcnicholas** [comment]
No, the Traceback does not look good. However, it depends on wether GroupIDs are allowed to be strings or just numbers. If strings should be valid, then we need to remove the validator (or replace with something quite sophisticated). If only numbers are allowed, then the warning is annoying but not serious - the validator should allow empty field somehow.

**Comment by MartinMalyMM** [comment]
I deleted the check whether the Group IDs are unique in prosmart_refmac_gui.py
I was wrong. As Rob N. pointed out, it’s ok for the Group IDs to not be unique - a user can combine multiple selections into one group (i.e. one occupancy to refine for all atoms in the grouped selections).

**Comment by MartinMalyMM** [comment]
> No, the Traceback does not look good. However, it depends on wether GroupIDs are allowed to be strings or just numbers. If strings should be valid, then we need to remove the validator (or replace with something quite sophisticated). If only numbers are allowed, then the warning is annoying but not serious - the validator should allow empty field somehow.

From Rob:
The Refmac documentation says that Group ID should be a “number”, which I took to mean integer. For the sake of the GUI I thought integer a reasonable choice - I can’t see what benefit would come from more flexibility in this case.

**Comment by paulsbond** [comment]
I guess just having an incorrect object as the validator makes Qt lock up that input. I'm not really sure why the regular expression is "^[1-9]+\d*" and not just "^[1-9]+" or "^\d+".

**Review by paulsbond — APPROVED** [review]

**Review by paulsbond — CHANGES_REQUESTED** [review]
Actually, we should probably fix the error message getting printed first?

**Review by paulsbond — APPROVED** [review]

**Comment by paulsbond** [comment]
I made a couple of changes if you are happy with them?

**Comment by MartinMalyMM** [comment]
Thank you

**Pull request merged**
